### ISSUE TITLE
Text (Asset name) Overlapping.

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#14]
Overlapping of text with in the asset details [Assets](http://mi-linux.wlv.ac.uk/~1700471/asset-tracker-web/asset/557)
![overlap1](https://user-images.githubusercontent.com/60874460/75921652-681c3200-5e59-11ea-9c7c-0b10e5c422c4.png)

And on the assets list page: [AssetsList](http://mi-linux.wlv.ac.uk/~1700471/asset-tracker-web/assets)

![overlap2](https://user-images.githubusercontent.com/60874460/75921681-710d0380-5e59-11ea-911b-a66093b3466c.png)

I wont do any more of theses test until I know how to remove them 😁 I best get back to what I should be doing 🤦‍♂

**Comment by JoshLmao** [comment]
Fixed both of these. Table should auto wrap the text
