### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by JoshLmao** [5CS024-Team1/asset-tracker-web#22]
- [x] Able to login/logout
- [x] Store a JWT token locally
- [x] JWT token contains expiry time
- [x] Create Profile page with user information
- [x] Able to change password of logged in user
- [ ] Password is encrypted before request
- [x] Backend: Verify signature on every request
- [x] Backend: Able to validate encrypted password to check if credentials are correct

**Comment by JoshLmao** [comment]
For more info on JWT and how they work: https://jwt.io/introduction/

**Comment by LuceMook87** [comment]
cheers for the link, interesting stuff!
