### ISSUE TITLE
Report Page

### ISSUE THREAD

**Issue by JoshLmao** [5CS024-Team1/asset-tracker-web#3]
Aim of the page is to schedule for collection of overdue assets.

- [x] Table of all overdue assets (Default table view)
- [x] Option to view overdue assets within a time range
- [x] Search by area

**Comment by MandyMoo3677** [comment]
Could this also be searched by area?  Should this further search criteria be a further development? Please advise.

**Comment by JoshLmao** [comment]
For the tables, each asset will display it's current area it's in so in theory searching by area can be done, once I get around to it 😉
