### ISSUE TITLE
Logo linking to homepage

### ISSUE THREAD

**Issue by 1827159** [5CS024-Team1/asset-tracker-web#35]
When clicking the logo, a usual function of a webpage would be that you are taken back to the homepage, this would be a great implementation.

If it is already in place, it didn't work for me.

**Comment by JoshLmao** [comment]
The text logo and the picture logo should link you back to the homepage. Try signing in, going to 'Assets' then clicking on the logo. Also, what browser are you using? (_I haven't crossed that bridge yet)

**Comment by 1827159** [comment]
I was using chrome but I was using it on my tablet (I WAS IN BED I AM IN LOCKDOWN LOL). Works all good on PC, looks really smart too! You've both done a great job.

Closing the issue as I don't expect the app to be fully functional on all platforms with the time we have, that would be ridiculous.
