### ISSUE TITLE
No Password Validation when creating user.

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#40]
New user passwords or changing passwords have no validation process to check length and complexity of password to prevent weak passwords being generated.

I would suggest passwords to be of min 8 characters long including numbers, small and capital lettering and special characters. Filtering of user input for common passwords to mitigate brute force/dictionary attacks. :smile:

**Comment by ghost** [comment]
I'll see if i can put that change in Phil

**Comment by ghost** [comment]
>Filtering of user input for common passwords to mitigate brute force/dictionary attacks. 😄

I might not quite have time to create a list of common passwords however the other changes are definitely achievable

**Comment by ghost** [comment]
53527d69c95a81c6f3f6cc778f76cb54620cd0ab - New commit now checks for validation

function checkPassword($password)
{
    if (strlen($password) >= 8) {
        if (preg_match('/[A-Za-z]/', $password) && preg_match('/[0-9]/', $password) && preg_match('/[\'\/~`\!@#\$%\^&\*\(\)_\-\+=\{\}\[\]\|;:"\<\>,\.\?\\\]/', $password)) {
            return TRUE;
        }
    }
    else {
        return FALSE;
    }
}

**Comment by Philwlv** [comment]
> Filtering of user input for common passwords to mitigate brute force/dictionary attacks. 😄
> 
> I might not quite have time to create a list of common passwords however the other changes are definitely achievable

Ye sorry, I'll put everything thing in that will be going in my report but I know some of them wont be manageable for our time restrictions, this might be something for future features maybe.

**Comment by Philwlv** [comment]
> 53527d6 - New commit now checks for validation
> function checkPassword($password)
> {
> if (strlen($password) >= 8) {
> if (preg_match('/[A-Za-z]/', $password) && preg_match('/[0-9]/', $password) && preg_match('/['/~`!@#$%^&*()_-+={}[]|;:"<>,.?\]/', $password)) {
> return TRUE;
> }
> }
> else {
> return FALSE;
> }
> }

Love it :smile: I'll be hopefully completing the testing today.
