### ISSUE TITLE
Aesthetic issue + search request

### ISSUE THREAD

**Issue by plasticpyrex** [5CS024-Team1/asset-tracker-web#41]
Not sure if this has been mentioned or can be remedied but on the homepage there is a large amount of blank white space

Another addition that may be of use is the ability to search the assets or by their type, category or location. If this has been requested or is unfeasible please disregard it.

**Comment by JoshLmao** [comment]
These are good suggestions. The home page does need more on there and I like the ability to search by type and category. Working on those now

**Comment by JoshLmao** [comment]
These are now done. Revamped the home page and added searching by category in search. Thanks Jamie
