### ISSUE TITLE
Functionality - reports page calender

### ISSUE THREAD

**Issue by MandyMoo3677** [5CS024-Team1/asset-tracker-web#44]
The calendar does not include the asset collection date (22/4/20). Is this because the date has passed?

**Comment by JoshLmao** [comment]
The current v0.1.2 site, this is broken. I can confirm in dev, this is fixed and will work with the next update. The reason was because we forgot to pass user authorization on this page

![image](https://user-images.githubusercontent.com/22716832/80798880-53c88d00-8b9d-11ea-9c9d-a632f7457120.png)
