### ISSUE TITLE
Unothorised access to user accounts.

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#47]
When calling the users profiles, the user id within the GET request can be changed (using a web app testing proxy) allowing the user to view other user's profiles.

This could be mitigated by checking and confirming that the id in the GET request matches the logged in user's id.

The proxy window shows the id veriable that's changed.
![ODR access other profiles 1](https://user-images.githubusercontent.com/60874460/80913656-26671500-8d3e-11ea-9084-1c9926dbecdd.png)

The profile page loaded belongs to user AD1 while the user that is logged in is STF3.

![ODR access other profiles 2](https://user-images.githubusercontent.com/60874460/80913661-2cf58c80-8d3e-11ea-8568-4abb2d433a75.png)

**Comment by JoshLmao** [comment]
Fixed both in 0d7c92ad14d49633fde26e49ff76a7ad4f6cc499 and in e9447bc770155396022d49714cfb815b4aa9223f, thanks for finding it Phil 😉
