### ISSUE TITLE
List of some testing issues.

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#49]
- Allocate asset does not seem to work
    An error message appears when trying to register an asset.
- Register assess needs input validation
     With the string entries, input would be better sanitized to prevent malicious input.  
- Registering asset id can be changed by user
 Isn't a big issue but, user can change an id to which they don't have permission to. 
- Register assets error displays sql query
Personally not been able to inject sql into the form however the error message displays the whole sql query which is extremely helpful for an attacker in understanding the database to guide attacks.
 ![Error Message is SQL query](https://user-images.githubusercontent.com/60874460/81346087-91ec1200-90b1-11ea-8145-3ff61d16a3de.png)
- asset id in reports is not numerical order
It has ordered as _1,10,2_,

- Admin unable to remove asset
Doesn't seem to be an ability to remove an asset.

**Comment by ghost** [comment]
> * Registering asset id can be changed by user
>   Isn't a big issue but, user can change an id to which they don't have permission to.

Just wondering do you mean the department ID as i'm unable to change the asset ID on both the live site and the Dev version?

**Comment by ghost** [comment]
> * Register assess needs input validation
>   With the string entries, input would be better sanitized to prevent malicious input.
> * Register assets error displays sql query
>   Personally not been able to inject sql into the form however the error message displays the whole sql query which is extremely helpful for an attacker in understanding the database to guide attacks.
>   ![Error Message is SQL query](https://user-images.githubusercontent.com/60874460/81346087-91ec1200-90b1-11ea-8145-3ff61d16a3de.png)

These two issues have been fixed by this commit - cb3682d0aee78b42d4f22b6fc3b0c610173b8e64

**Comment by ghost** [comment]
> * Registering asset id can be changed by user
>   Isn't a big issue but, user can change an id to which they don't have permission to.

This commit changes when the ID is fetched from the DB, no matter what is posted from the UI it will be overwritten - e7ed974ded4ebdaca3e53b21a7c0d9262c43319b

**Comment by ghost** [comment]
> * asset id in reports is not numerical order
>   It has ordered as _1,10,2_,

Changed datatype, now sorts correctly in numerical order not text order - 309755408b54a1304d33e99be92606dbfe32fe40

**Comment by ghost** [comment]
> * Admin unable to remove asset
>   Doesn't seem to be an ability to remove an asset.

If doesn't seem like we'll have time at this stage to implement the removal of assets if that's okay with you Phil

**Comment by Philwlv** [comment]
> Admin unable to remove asset
> Doesn't seem to be an ability to remove an asset.
> 
> 
> If doesn't seem like we'll have time at this stage to implement the removal of assets if that's okay with you Phil


Hey Matt, I'm sure I answered all these for you through an alternative communication. But Great job on sorting these out! No worries about this last one, future development maybe @plasticpyrex ?
