### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by MandyMoo3677** [5CS024-Team1/asset-tracker-web#51]
Can we please add 5 records for patients, products, and hospitals please.  Can we have 1 patent and 1 hospital to have a product allocated.  Can 1 of the allocated products be overdue?

**Comment by ghost** [comment]
I'll work on this as soon as the final change has been made to the DB

**Comment by ghost** [comment]
I've set up one as neither overdue or out of zone, one as out of zone but not overdue and one as out of zone but not overdue. There are also two other assets which have not been assigned and so are in hospital. There are 6 accounts - 3 for Sherin, Steve and Alix and 3 other accounts. There are 5 Hospitals as well - a658b7ebc8ef924254540088ef4afde1f71cb785
