### ISSUE TITLE
User permissions and users

### ISSUE THREAD

**Issue by MandyMoo3677** [5CS024-Team1/asset-tracker-web#53]
Apologies for lateness in this request.

Can we please have three users types?
Admin: 
     Dashboard, Assets, Register, Reports, Users
Asset Mgmt Team:
     Dashboard. Assets, Register Asset, Reports
Staff User:
     Dashboard, Assets, Reports.

Can you please add three new users - Alix, Sherin and Steve? Please email me there login and passwords.

**Comment by JoshLmao** [comment]
I've added the management user type in b13d6c06f481516e875feedd0e86476efe0126d1. I'll leave this issue open since I haven't added the three new users yet

**Comment by ghost** [comment]
New accounts have been made i'll email through the login - a658b7ebc8ef924254540088ef4afde1f71cb785
