### ISSUE TITLE
Is Attribute input user input?

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#6]
https://github.com/5CS024-Team1/asset-tracker-web/blob/53b5078c487b3076a96e9ac574b3d85dd631525a/api/assets/allocate/index.php#L20 Are the attributes user input? this will need sanitizing and filtering with in the function if so. 😄

**Comment by JoshLmao** [comment]
Yes, they are. I'll amend issue #7 to be a general sanitizing/filtering to do so if you find any more, reference it in there

**Comment by Philwlv** [comment]
Awesome, I'm still getting use to this platform so I'll prob be a annoyingly amateurish for a good while 😄
