### ISSUE TITLE
SQL filtering on function needed. (General PHP Sanitizing/Filtering)

### ISSUE THREAD

**Issue by Philwlv** [5CS024-Team1/asset-tracker-web#7]
https://github.com/5CS024-Team1/asset-tracker-web/blob/53b5078c487b3076a96e9ac574b3d85dd631525a/api/assets/allocate/index.php#L29
_$post_ and _$address_ will need filtering and sanitizing or placed in a prepared statement. If these are user input, to mitigate from SQL injection.

**Comment by JoshLmao** [comment]
Yeah, I agree. I'll add it to the "To Do" list. Good catch

**Comment by JoshLmao** [comment]
GetFullAddress also requires sanitized input (from #6 )
https://github.com/5CS024-Team1/asset-tracker-web/blob/53b5078c487b3076a96e9ac574b3d85dd631525a/api/assets/allocate/index.php#L20-L26

**Comment by Philwlv** [comment]
Is there a way I can grab the whole function rather that pullin the first line up? or is this how I should be doing these? just wondering how I should be doing these??

**Comment by JoshLmao** [comment]
Yes, you can reference more than one line [Check this out](https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet). Tl:dr you can, select a range of lines using shift

**Comment by Philwlv** [comment]
Perfect

**Comment by Philwlv** [comment]
Just give me a heads up if I'm not reporting things right. I had a look at the security section but I'm not sure how to use that or if it needs setting up? is that something I could do?

**Comment by JoshLmao** [comment]
The Security tab is an automated Github thing that notifies us if we're using an outdated package with security vulnerabilities. There isn't much else in there. 

How you're doing it is correct! I've just added a special Label for any security issues you have so feel free to start using that if you open any new issues about security

**Comment by Philwlv** [comment]
Perfect! erm.. how do I attach a label? I couldn't fathom it out last night 🤦‍♂

**Comment by JoshLmao** [comment]
Oh, i didn't realize. I've given you access to the repo now which should allow you to do it

**Comment by Philwlv** [comment]
Yes! I get it now 😁 Awesome. I'll drop into the code ever couple of days and go through it. Or did you want to highlight a section you have mostly done for me to go over first ect..?

**Comment by JoshLmao** [comment]
For sprint 1, I'm focused on the front end right now while Matt is on the back end. I suggest checking to see when he commits for new code. I don't think any of the back end is **final** so but i guess it wouldn't hurt to do a check every week or so?
